apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: clusterwatch
  namespace: clusterwatch
spec:
  ingressClassName: nginx
  rules:
    - host: app.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service: { name: clusterwatch-frontend, port: { number: 80 } }
    - host: api.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service: { name: clusterwatch-backend, port: { number: 80 } }
