apiVersion: v1
kind: Service
metadata:
  name: clusterwatch-backend
  namespace: clusterwatch
spec:
  selector: { app: clusterwatch-backend }
  ports: [{ port: 80, targetPort: http }]
---
apiVersion: v1
kind: Service
metadata:
  name: clusterwatch-frontend
  namespace: clusterwatch
spec:
  selector: { app: clusterwatch-frontend }
  ports: [{ port: 80, targetPort: http }]
