apiVersion: v1
kind: Service
metadata:
  name: clusterwatch-frontend
  namespace: {{ .Release.Namespace }}
spec:
  selector: { app: clusterwatch-frontend }
  ports:
    - name: http
      port: 80
      targetPort: http
