{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: clusterwatch
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: {{ .Values.ingress.className | quote }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - secretName: {{ .Values.ingress.tls.secretName | quote }}
      hosts:
{{- range .Values.ingress.hosts }}
        - {{ .host | quote }}
{{- end }}
  {{- end }}
  rules:
{{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
{{- range .paths }}
          - path: {{ .path | quote }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ ternary "clusterwatch-frontend" "clusterwatch-backend" (eq .service "frontend") }}
                port: { number: 80 }
{{- end }}
{{- end }}
{{- end }}
